version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "23:30"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.19
    - 14.14.22
  - dependency-name: typescript
    versions:
    - 4.1.3
  - dependency-name: "@types/mongodb"
    versions:
    - 3.6.3
  - dependency-name: "@types/express"
    versions:
    - 4.17.9
  - dependency-name: mongodb
    versions:
    - 3.6.3
  - dependency-name: "@types/node-fetch"
    versions:
    - 2.5.7
